/**
 * \file
 *
 * \brief AUTOSAR FrTp
 *
 * This file contains the implementation of the AUTOSAR
 * module FrTp.
 *
 * \version 4.4.26
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2021 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */
/* Editing futile - file generated by 'make compile' */

#ifndef FRTP_MERGED_INCLUDES_H
#define FRTP_MERGED_INCLUDES_H

/* BEWARE: if you think, you see duplicates only differing in case:
 * there are case-sensitive OSes - so fix the case!
 * Indented files stem from the merged_includes_foreign file in your
 * source tree and signify externally visible API files
 */

#include <TSMem.h>
#include <Std_Types.h>
#include <SchM_FrTp.h>
#include <PduR_FrTp.h>
#include <FrIf.h>
#include <Base_Dbg.h>

#endif /* defined FRTP_MERGED_INCLUDES_H */
