/* kern-errext-KillAlarm.c - kernel error database for STATUS=EXTENDED
 *
 * This is a generated file - DO NOT EDIT
 *
 * Generated by errdb-to-c.pl on 2020-03-03 16:30
 *
 * (c) 2020 Elektrobit Automotive GmbH
*/

#include <Os_kernel.h>
#include <Os_error.h>

#include <memmap/Os_mm_const_begin.h>
static const os_errorentry_t OS_errtblKillAlarm[1] =
{
  {
    OS_E_INTERNAL,
    OS_ERROR_AlarmNotInQueue,
    OS_ACTION_SHUTDOWN|OS_ACTION_ERRORHOOK
  }
};

const os_serviceinfo_t OS_svc_KillAlarm =
{
    OS_errtblKillAlarm,
    OS_SID_KillAlarm,
    1
};
#include <memmap/Os_mm_const_end.h>
