/* kern-erruni-TaskReturn.c - kernel error database for STATUS=UNIVERSAL
 *
 * This is a generated file - DO NOT EDIT
 *
 * Generated by errdb-to-c.pl on 2020-03-03 16:30
 *
 * (c) 2020 Elektrobit Automotive GmbH
*/

#include <Os_kernel.h>
#include <Os_error.h>

#include <memmap/Os_mm_const_begin.h>
static const os_errorentry_t OS_errtblTaskReturn[1] =
{
  {
    OS_E_TASKRETURN,
    OS_ERROR_ReturnFromTask,
    OS_ACTION_QUARANTINE|OS_ACTION_ERRORHOOK
  }
};

const os_serviceinfo_t OS_svc_TaskReturn =
{
    OS_errtblTaskReturn,
    OS_SID_TaskReturn,
    1
};
#include <memmap/Os_mm_const_end.h>
