/* Os_errorcodes.h - kernel error code translations
 *
 * This is a generated file - DO NOT EDIT
 *
 * Generated by errdb-to-c.pl on 2020-03-03 16:30
 *
 * (c) 2020 Elektrobit Automotive GmbH
*/

#if defined(OS_SID) && !defined(OS_ERRORCODES_H)
#define OS_ERRORCODES_H

#ifndef OS_SID_EC
#define OS_SID_EC OS_SID
#endif

#include <Os_error.h>
#include <Os_errorcodes_arch.h>


#if OS_SID_EC == OS_SID_UnknownSyscall
#define OS_EC_OS_ERROR_UnknownSystemCall            OS_E_NOFUNC
#endif

#if OS_SID_EC == OS_SID_ActivateTask
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidTaskId                OS_E_ID
#define OS_EC_OS_ERROR_Quarantined                  OS_E_DENIED
#define OS_EC_OS_ERROR_MaxActivations               OS_E_LIMIT
#define OS_EC_OS_ERROR_RateLimitExceeded            OS_E_RATEPROT
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#endif

#if OS_SID_EC == OS_SID_TerminateTask
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_HoldsLock                    OS_E_SPINLOCK
#define OS_EC_OS_ERROR_HoldsResource                OS_E_RESOURCE
#endif

#if OS_SID_EC == OS_SID_ChainTask
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_HoldsLock                    OS_E_SPINLOCK
#define OS_EC_OS_ERROR_HoldsResource                OS_E_RESOURCE
#define OS_EC_OS_ERROR_InvalidTaskId                OS_E_ID
#define OS_EC_OS_ERROR_Quarantined                  OS_E_DENIED
#define OS_EC_OS_ERROR_MaxActivations               OS_E_LIMIT
#define OS_EC_OS_ERROR_RateLimitExceeded            OS_E_RATEPROT
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#endif

#if OS_SID_EC == OS_SID_GetTaskState
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#define OS_EC_OS_ERROR_InvalidTaskId                OS_E_ID
#endif

#if OS_SID_EC == OS_SID_Schedule
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_HoldsLock                    OS_E_SPINLOCK
#define OS_EC_OS_ERROR_HoldsResource                OS_E_RESOURCE
#endif

#if OS_SID_EC == OS_SID_GetAlarm
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#define OS_EC_OS_ERROR_InvalidAlarmId               OS_E_ID
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_InvalidAlarmState            OS_E_PANIC
#define OS_EC_OS_ERROR_AlarmNotInUse                OS_E_NOFUNC
#endif

#if OS_SID_EC == OS_SID_GetAlarmBase
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#define OS_EC_OS_ERROR_InvalidAlarmId               OS_E_ID
#endif

#if OS_SID_EC == OS_SID_CancelAlarm
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidAlarmId               OS_E_ID
#define OS_EC_OS_ERROR_AlarmNotInUse                OS_E_NOFUNC
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#endif

#if OS_SID_EC == OS_SID_SetRelAlarm
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidAlarmId               OS_E_ID
#define OS_EC_OS_ERROR_IncrementZero                OS_E_VALUE
#define OS_EC_OS_ERROR_ParameterOutOfRange          OS_E_VALUE
#define OS_EC_OS_ERROR_Quarantined                  OS_E_DENIED
#define OS_EC_OS_ERROR_AlarmInUse                   OS_E_STATE
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#endif

#if OS_SID_EC == OS_SID_SetAbsAlarm
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidAlarmId               OS_E_ID
#define OS_EC_OS_ERROR_ParameterOutOfRange          OS_E_VALUE
#define OS_EC_OS_ERROR_Quarantined                  OS_E_DENIED
#define OS_EC_OS_ERROR_AlarmInUse                   OS_E_STATE
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#endif

#if OS_SID_EC == OS_SID_GetResource
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidResourceId            OS_E_ID
#define OS_EC_OS_ERROR_ResourceInUse                OS_E_ACCESS
#define OS_EC_OS_ERROR_ResourcePriorityError        OS_E_ACCESS
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#endif

#if OS_SID_EC == OS_SID_ReleaseResource
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidResourceId            OS_E_ID
#define OS_EC_OS_ERROR_ResourceNestingError         OS_E_NOFUNC
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#endif

#if OS_SID_EC == OS_SID_WaitEvent
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_NoEvents                     OS_E_VALUE
#define OS_EC_OS_ERROR_TaskNotExtended              OS_E_ACCESS
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_HoldsLock                    OS_E_SPINLOCK
#define OS_EC_OS_ERROR_HoldsResource                OS_E_RESOURCE
#define OS_EC_OS_ERROR_RateLimitExceeded            OS_E_RATEPROT
#endif

#if OS_SID_EC == OS_SID_SetEvent
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidTaskId                OS_E_ID
#define OS_EC_OS_ERROR_TaskSuspended                OS_E_STATE
#define OS_EC_OS_ERROR_TaskNotExtended              OS_E_ACCESS
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_RateLimitExceeded            OS_E_RATEPROT
#endif

#if OS_SID_EC == OS_SID_GetEvent
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidTaskId                OS_E_ID
#define OS_EC_OS_ERROR_TaskNotExtended              OS_E_ACCESS
#define OS_EC_OS_ERROR_TaskSuspended                OS_E_STATE
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#endif

#if OS_SID_EC == OS_SID_ClearEvent
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_TaskNotExtended              OS_E_ACCESS
#endif

#if OS_SID_EC == OS_SID_StartOs
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidStartMode             OS_E_ID
#endif

#if OS_SID_EC == OS_SID_ShutdownOs
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_NotTrusted                   OS_E_NOFUNC
#endif

#if OS_SID_EC == OS_SID_SuspendInterrupts
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_NestingOverflow              OS_E_NOFUNC
#endif

#if OS_SID_EC == OS_SID_ResumeInterrupts
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_NestingUnderflow             OS_E_NOFUNC
#endif

#if OS_SID_EC == OS_SID_IncrementCounter
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidCounterId             OS_E_ID
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_CounterIsHw                  OS_E_ID
#endif

#if OS_SID_EC == OS_SID_GetStackInfo
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#define OS_EC_OS_ERROR_InvalidTaskId                OS_E_ID
#define OS_EC_OS_ERROR_InvalidIsrId                 OS_E_ID
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#endif

#if OS_SID_EC == OS_SID_IsrHandler
#define OS_EC_OS_ERROR_InsufficientStack            OS_E_STACKPROT
#define OS_EC_OS_ERROR_RateLimitExceeded            OS_E_RATEPROT
#define OS_EC_OS_ERROR_HoldsLock                    OS_E_ISRRETURNSPINLOCKED
#define OS_EC_OS_ERROR_HoldsResource                OS_E_ISRRETURNRESLOCKED
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_ISRRETURNINTLOCKED
#define OS_EC_OS_ERROR_KernelStackOverflow          OS_E_STACKPROT
#endif

#if OS_SID_EC == OS_SID_HookHandler
#define OS_EC_OS_ERROR_InsufficientStack            OS_E_STACKPROT
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#endif

#if OS_SID_EC == OS_SID_Dispatch
#define OS_EC_OS_ERROR_KernelStackOverflow          OS_E_STACKPROT
#define OS_EC_OS_ERROR_TaskStackOverflow            OS_E_STACKPROT
#endif

#if OS_SID_EC == OS_SID_TrapHandler
#define OS_EC_OS_ERROR_UnknownInterrupt             OS_E_INTERNAL
#define OS_EC_OS_ERROR_TaskTimeBudgetExceeded       OS_E_TIMEPROT
#define OS_EC_OS_ERROR_TaskResLockTimeExceeded      OS_E_LOCKPROT
#define OS_EC_OS_ERROR_TaskIntLockTimeExceeded      OS_E_LOCKPROT
#define OS_EC_OS_ERROR_IsrTimeBudgetExceeded        OS_E_TIMEPROT
#define OS_EC_OS_ERROR_IsrResLockTimeExceeded       OS_E_LOCKPROT
#define OS_EC_OS_ERROR_IsrIntLockTimeExceeded       OS_E_LOCKPROT
#endif

#if OS_SID_EC == OS_SID_ChainScheduleTable
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidScheduleId            OS_E_ID
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_DifferentCounters            OS_E_ID
#define OS_EC_OS_ERROR_NotRunning                   OS_E_NOFUNC
#define OS_EC_OS_ERROR_NotStopped                   OS_E_STATE
#endif

#if OS_SID_EC == OS_SID_StartScheduleTableRel
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_ScheduleTableNotIdle         OS_E_STATE
#define OS_EC_OS_ERROR_AlarmInUse                   OS_E_STATE
#define OS_EC_OS_ERROR_InvalidScheduleId            OS_E_ID
#define OS_EC_OS_ERROR_ParameterOutOfRange          OS_E_VALUE
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_ImplicitSyncStartRel         OS_E_ID
#endif

#if OS_SID_EC == OS_SID_StartScheduleTableAbs
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_ScheduleTableNotIdle         OS_E_STATE
#define OS_EC_OS_ERROR_AlarmInUse                   OS_E_STATE
#define OS_EC_OS_ERROR_InvalidScheduleId            OS_E_ID
#define OS_EC_OS_ERROR_ParameterOutOfRange          OS_E_VALUE
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_ImplicitSyncStartRel         OS_E_ID
#endif

#if OS_SID_EC == OS_SID_StartScheduleTableSynchron
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_ScheduleTableNotIdle         OS_E_STATE
#define OS_EC_OS_ERROR_AlarmInUse                   OS_E_STATE
#define OS_EC_OS_ERROR_InvalidScheduleId            OS_E_ID
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_NotSyncable                  OS_E_ID
#endif

#if OS_SID_EC == OS_SID_RunSchedule
#define OS_EC_OS_ERROR_NotChained                   OS_E_STATE
#endif

#if OS_SID_EC == OS_SID_StopScheduleTable
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidScheduleId            OS_E_ID
#define OS_EC_OS_ERROR_NotRunning                   OS_E_NOFUNC
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#endif

#if OS_SID_EC == OS_SID_CheckObjectOwnership
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidObjectType            OS_E_VALUE
#define OS_EC_OS_ERROR_InvalidObjectId              OS_E_ID
#endif

#if OS_SID_EC == OS_SID_CheckObjectAccess
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidObjectId              OS_E_ID
#define OS_EC_OS_ERROR_InvalidObjectType            OS_E_VALUE
#define OS_EC_OS_ERROR_InvalidApplicationId         OS_E_ID
#endif

#if OS_SID_EC == OS_SID_CheckTaskMemoryAccess
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidTaskId                OS_E_ID
#define OS_EC_OS_ERROR_InvalidMemoryRegion          OS_E_VALUE
#endif

#if OS_SID_EC == OS_SID_CheckIsrMemoryAccess
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidIsrId                 OS_E_ID
#define OS_EC_OS_ERROR_InvalidMemoryRegion          OS_E_VALUE
#endif

#if OS_SID_EC == OS_SID_TerminateApplication
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_STATE
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidApplicationId         OS_E_ID
#define OS_EC_OS_ERROR_InvalidRestartOption         OS_E_VALUE
#endif

#if OS_SID_EC == OS_SID_KillAlarm
#define OS_EC_OS_ERROR_AlarmNotInQueue              OS_E_INTERNAL
#endif

#if OS_SID_EC == OS_SID_CallTrustedFunction
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_InvalidFunctionId            OS_E_TFID
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_StackError                   OS_E_STACKPROT
#define OS_EC_OS_ERROR_CallTrustedFunctionCrosscore    OS_E_ACCESS
#endif

#if OS_SID_EC == OS_SID_GetScheduleTableStatus
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidScheduleId            OS_E_ID
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#endif

#if OS_SID_EC == OS_SID_SetScheduleTableAsync
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidScheduleId            OS_E_ID
#define OS_EC_OS_ERROR_NotRunning                   OS_E_STATE
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_NotSyncable                  OS_E_ID
#endif

#if OS_SID_EC == OS_SID_SyncScheduleTable
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_InvalidScheduleId            OS_E_ID
#define OS_EC_OS_ERROR_NotRunning                   OS_E_STATE
#define OS_EC_OS_ERROR_NotSyncable                  OS_E_ID
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_ParameterOutOfRange          OS_E_VALUE
#endif

#if OS_SID_EC == OS_SID_GetTaskId
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#endif

#if OS_SID_EC == OS_SID_GetActiveApplicationMode
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#endif

#if OS_SID_EC == OS_SID_GetIsrId
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#endif

#if OS_SID_EC == OS_SID_GetApplicationId
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#endif

#if OS_SID_EC == OS_SID_TaskReturn
#define OS_EC_OS_ERROR_ReturnFromTask               OS_E_TASKRETURN
#endif

#if OS_SID_EC == OS_SID_DisableInterruptSource
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_InvalidIsrId                 OS_E_ID
#endif

#if OS_SID_EC == OS_SID_EnableInterruptSource
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_InvalidIsrId                 OS_E_ID
#endif

#if OS_SID_EC == OS_SID_GetCounterValue
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#define OS_EC_OS_ERROR_InvalidCounterId             OS_E_ID
#endif

#if OS_SID_EC == OS_SID_GetElapsedCounterValue
#define OS_EC_OS_ERROR_ApplicationNotAccessible     OS_E_ACCESS
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#define OS_EC_OS_ERROR_InvalidCounterId             OS_E_ID
#define OS_EC_OS_ERROR_ParameterOutOfRange          OS_E_VALUE
#endif

#if OS_SID_EC == OS_SID_TryToGetSpinlock
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#define OS_EC_OS_ERROR_InvalidSpinlockId            OS_E_ID
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_InvalidSpinlockNesting       OS_E_NESTING_DEADLOCK
#define OS_EC_OS_ERROR_SpinlockAlreadyHeld          OS_E_STATE
#define OS_EC_OS_ERROR_SpinlockInterferenceDeadlock    OS_E_INTERFERENCE_DEADLOCK
#endif

#if OS_SID_EC == OS_SID_ReleaseSpinlock
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InvalidSpinlockId            OS_E_ID
#define OS_EC_OS_ERROR_Permission                   OS_E_ACCESS
#define OS_EC_OS_ERROR_SpinlockNotOccupied          OS_E_STATE
#define OS_EC_OS_ERROR_InvalidSpinlockNesting       OS_E_NOFUNC
#define OS_EC_OS_ERROR_HoldsResource                OS_E_RESOURCE
#endif

#if OS_SID_EC == OS_SID_AllowAccess
#define OS_EC_OS_ERROR_ApplicationNotRestarting     OS_E_STATE
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#endif

#if OS_SID_EC == OS_SID_GetApplicationState
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_InvalidApplicationId         OS_E_ID
#define OS_EC_OS_ERROR_WriteProtect                 OS_E_ADDRESS
#endif

#if OS_SID_EC == OS_SID_ShutdownAllCores
#define OS_EC_OS_ERROR_WrongContext                 OS_E_CALLLEVEL
#define OS_EC_OS_ERROR_InterruptDisabled            OS_E_INTDISABLE
#define OS_EC_OS_ERROR_NotTrusted                   OS_E_NOFUNC
#endif

#if OS_SID_EC == OS_SID_GetCpuLoad
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_InvalidCoreId                OS_E_ID
#endif

#if OS_SID_EC == OS_SID_ResetPeakCpuLoad
#define OS_EC_OS_ERROR_CoreIsDown                   OS_E_CORE
#define OS_EC_OS_ERROR_InvalidCoreId                OS_E_ID
#endif

#endif
