/**
 * \file
 *
 * \brief AUTOSAR FrSM
 *
 * This file contains the implementation of the AUTOSAR
 * module FrSM.
 *
 * \version 5.3.18
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2021 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */
/* Editing futile - file generated by 'make compile' */

#ifndef FRSM_GUARDS_H
#define FRSM_GUARDS_H

#ifdef FRSM_CLSTIDX
  #error FRSM_CLSTIDX already defined
#endif

#ifdef FRSM_DET_REPORTERROR
  #error FRSM_DET_REPORTERROR already defined
#endif

#ifdef FRSM_DET_REPORTERROR_WITH_INSTANCE
  #error FRSM_DET_REPORTERROR_WITH_INSTANCE already defined
#endif

#ifdef FRSM_INIT
  #error FRSM_INIT already defined
#endif

#ifdef FRSM_INSTANCE_ID
  #error FRSM_INSTANCE_ID already defined
#endif

#ifdef FRSM_INTERNAL_API_ID
  #error FRSM_INTERNAL_API_ID already defined
#endif

#ifdef FRSM_INVALID_DEM_EVENTID
  #error FRSM_INVALID_DEM_EVENTID already defined
#endif

#ifdef FRSM_INVARIANT_ASSERT
  #error FRSM_INVARIANT_ASSERT already defined
#endif

#ifdef FRSM_INVARIANT_ASSERT_NO_EVAL
  #error FRSM_INVARIANT_ASSERT_NO_EVAL already defined
#endif

#ifdef FRSM_OPTIONS_CHECK_WAKEUP_REASON
  #error FRSM_OPTIONS_CHECK_WAKEUP_REASON already defined
#endif

#ifdef FRSM_OPTIONS_DELAY_STARTUP_WO_WAKEUP
  #error FRSM_OPTIONS_DELAY_STARTUP_WO_WAKEUP already defined
#endif

#ifdef FRSM_OPTIONS_IS_COLDSTART_ECU
  #error FRSM_OPTIONS_IS_COLDSTART_ECU already defined
#endif

#ifdef FRSM_OPTIONS_IS_DUAL_CHANNEL_NODE
  #error FRSM_OPTIONS_IS_DUAL_CHANNEL_NODE already defined
#endif

#ifdef FRSM_OPTIONS_IS_WAKEUP_ECU
  #error FRSM_OPTIONS_IS_WAKEUP_ECU already defined
#endif

#ifdef FRSM_OPTIONS_TRCV_CHANNEL_A
  #error FRSM_OPTIONS_TRCV_CHANNEL_A already defined
#endif

#ifdef FRSM_OPTIONS_TRCV_CHANNEL_B
  #error FRSM_OPTIONS_TRCV_CHANNEL_B already defined
#endif

#ifdef FRSM_POSTCONDITION_ASSERT
  #error FRSM_POSTCONDITION_ASSERT already defined
#endif

#ifdef FRSM_POSTCONDITION_ASSERT_NO_EVAL
  #error FRSM_POSTCONDITION_ASSERT_NO_EVAL already defined
#endif

#ifdef FRSM_PRECONDITION_ASSERT
  #error FRSM_PRECONDITION_ASSERT already defined
#endif

#ifdef FRSM_PRECONDITION_ASSERT_NO_EVAL
  #error FRSM_PRECONDITION_ASSERT_NO_EVAL already defined
#endif

#ifdef FRSM_REPETITIONS_INFINITE_VALUE
  #error FRSM_REPETITIONS_INFINITE_VALUE already defined
#endif

#ifdef FRSM_SID_ALLSLOTS
  #error FRSM_SID_ALLSLOTS already defined
#endif

#ifdef FRSM_SID_GETCURRENTCOMMODE
  #error FRSM_SID_GETCURRENTCOMMODE already defined
#endif

#ifdef FRSM_SID_GETVERSIONINFO
  #error FRSM_SID_GETVERSIONINFO already defined
#endif

#ifdef FRSM_SID_INIT
  #error FRSM_SID_INIT already defined
#endif

#ifdef FRSM_SID_MAINFUNCTION
  #error FRSM_SID_MAINFUNCTION already defined
#endif

#ifdef FRSM_SID_REQUESTCOMMODE
  #error FRSM_SID_REQUESTCOMMODE already defined
#endif

#ifdef FRSM_SID_SETECUPASSIVE
  #error FRSM_SID_SETECUPASSIVE already defined
#endif

#ifdef FRSM_STATEMACHINE_LOCK
  #error FRSM_STATEMACHINE_LOCK already defined
#endif

#ifdef FRSM_STATEMACHINE_MAINFUNCTION_SUSPENDED
  #error FRSM_STATEMACHINE_MAINFUNCTION_SUSPENDED already defined
#endif

#ifdef FRSM_STATEMACHINE_REQUESTCOMMODE_SUSPENDED
  #error FRSM_STATEMACHINE_REQUESTCOMMODE_SUSPENDED already defined
#endif

#ifdef FRSM_STATEMACHINE_RESET
  #error FRSM_STATEMACHINE_RESET already defined
#endif

#ifdef FRSM_STATE_HALT_REQ
  #error FRSM_STATE_HALT_REQ already defined
#endif

#ifdef FRSM_STATE_KEYSLOT_ONLY
  #error FRSM_STATE_KEYSLOT_ONLY already defined
#endif

#ifdef FRSM_STATE_NUMSTATES
  #error FRSM_STATE_NUMSTATES already defined
#endif

#ifdef FRSM_STATE_ONLINE
  #error FRSM_STATE_ONLINE already defined
#endif

#ifdef FRSM_STATE_ONLINE_PASSIVE
  #error FRSM_STATE_ONLINE_PASSIVE already defined
#endif

#ifdef FRSM_STATE_READY
  #error FRSM_STATE_READY already defined
#endif

#ifdef FRSM_STATE_STARTUP
  #error FRSM_STATE_STARTUP already defined
#endif

#ifdef FRSM_STATE_WAKEUP
  #error FRSM_STATE_WAKEUP already defined
#endif

#ifdef FRSM_STATIC_ASSERT
  #error FRSM_STATIC_ASSERT already defined
#endif

#ifdef FRSM_T3_NOTACTIVE
  #error FRSM_T3_NOTACTIVE already defined
#endif

#ifdef FRSM_TRCV_STATE_IDX
  #error FRSM_TRCV_STATE_IDX already defined
#endif

#ifdef FRSM_UNINIT
  #error FRSM_UNINIT already defined
#endif

#ifdef FRSM_UNREACHABLE_CODE_ASSERT
  #error FRSM_UNREACHABLE_CODE_ASSERT already defined
#endif

#ifdef FrSM_FE_DEM_SYNC_LOSS
  #error FrSM_FE_DEM_SYNC_LOSS already defined
#endif

#ifdef FrSM_FE_DEM_SYNC_LOSS_PASSED
  #error FrSM_FE_DEM_SYNC_LOSS_PASSED already defined
#endif

#endif /* defined FRSM_GUARDS_H */
