/**
 * \file
 *
 * \brief AUTOSAR FrSM
 *
 * This file contains the implementation of the AUTOSAR
 * module FrSM.
 *
 * \version 5.3.18
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2021 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */
/* Editing futile - file generated by 'make compile' */

#ifndef FRSM_MERGED_INCLUDES_H
#define FRSM_MERGED_INCLUDES_H

/* BEWARE: if you think, you see duplicates only differing in case:
 * there are case-sensitive OSes - so fix the case!
 * Indented files stem from the merged_includes_foreign file in your
 * source tree and signify externally visible API files
 */

#include FRSM_SYNC_LOSS_ERROR_INDICATION_HEADER
#include <TSAtomic_Assign.h>
#include <Std_Types.h>
#include <SchM_FrSM.h>
#include <FrNm.h>
#include <FrIf.h>
#include <Det.h>
#include <Dem.h>
#include <ComM_BusSm.h>
#include <BswM_FrSM.h>
#include <Base_Dbg.h>

#endif /* defined FRSM_MERGED_INCLUDES_H */
