/* Os_errorcodes_WINDOWS.h - kernel error code translations
 *
 * This is a generated file - DO NOT EDIT
 *
 * Generated by errdb-to-c.pl on 2020-03-03 16:30
 *
 * (c) 2020 Elektrobit Automotive GmbH
*/

#if defined(OS_SID) && !defined(OS_ERRORCODES_WINDOWS_H)
#define OS_ERRORCODES_WINDOWS_H

#ifndef OS_SID_EC
#define OS_SID_EC OS_SID
#endif

#include <Os_error.h>


#endif
