/**
 * \file
 *
 * \brief AUTOSAR FrIf
 *
 * This file contains the implementation of the AUTOSAR
 * module FrIf.
 *
 * \version 5.3.25
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2021 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */
/* Editing futile - file generated by 'make compile' */

#ifndef FRIF_MERGED_INCLUDES_H
#define FRIF_MERGED_INCLUDES_H

/* BEWARE: if you think, you see duplicates only differing in case:
 * there are case-sensitive OSes - so fix the case!
 * Indented files stem from the merged_includes_foreign file in your
 * source tree and signify externally visible API files
 */

#include <TSPBConfig_Signature.h>
#include <TSMem.h>
#include <TSAutosar.h>
#include <TSAtomic_Assign.h>
#include <Std_Types.h>
#include <SchM_FrIf.h>
#include <Base_Dbg.h>

#endif /* defined FRIF_MERGED_INCLUDES_H */
