/**
 * \file
 *
 * \brief AUTOSAR FrIf
 *
 * This file contains the implementation of the AUTOSAR
 * module FrIf.
 *
 * \version 5.3.25
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2021 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */
/* Editing futile - file generated by 'make compile' */

#ifndef FRIF_GUARDS_H
#define FRIF_GUARDS_H

#ifdef FRIF_CHANNEL_STATUS_DEM_REPORTING
  #error FRIF_CHANNEL_STATUS_DEM_REPORTING already defined
#endif

#ifdef FRIF_CHANNEL_STATUS_REPORTING
  #error FRIF_CHANNEL_STATUS_REPORTING already defined
#endif

#ifdef FRIF_CHNL_STAT_ACS_AC
  #error FRIF_CHNL_STAT_ACS_AC already defined
#endif

#ifdef FRIF_CHNL_STAT_ACS_BV
  #error FRIF_CHNL_STAT_ACS_BV already defined
#endif

#ifdef FRIF_CHNL_STAT_ACS_CE
  #error FRIF_CHNL_STAT_ACS_CE already defined
#endif

#ifdef FRIF_CHNL_STAT_ACS_SE
  #error FRIF_CHNL_STAT_ACS_SE already defined
#endif

#ifdef FRIF_CHNL_STAT_ACS_TC
  #error FRIF_CHNL_STAT_ACS_TC already defined
#endif

#ifdef FRIF_CHNL_STAT_ACS_VF
  #error FRIF_CHNL_STAT_ACS_VF already defined
#endif

#ifdef FRIF_CHNL_STAT_NIT_BV
  #error FRIF_CHNL_STAT_NIT_BV already defined
#endif

#ifdef FRIF_CHNL_STAT_NIT_SE
  #error FRIF_CHNL_STAT_NIT_SE already defined
#endif

#ifdef FRIF_CHNL_STAT_SW_BV
  #error FRIF_CHNL_STAT_SW_BV already defined
#endif

#ifdef FRIF_CHNL_STAT_SW_SE
  #error FRIF_CHNL_STAT_SW_SE already defined
#endif

#ifdef FRIF_CHNL_STAT_SW_TC
  #error FRIF_CHNL_STAT_SW_TC already defined
#endif

#ifdef FRIF_CHNL_STAT_SW_VM
  #error FRIF_CHNL_STAT_SW_VM already defined
#endif

#ifdef FRIF_CLSTIDX
  #error FRIF_CLSTIDX already defined
#endif

#ifdef FRIF_CONST_CFG_ADDRESS_ENABLE
  #error FRIF_CONST_CFG_ADDRESS_ENABLE already defined
#endif

#ifdef FRIF_CTRLIDX
  #error FRIF_CTRLIDX already defined
#endif

#ifdef FRIF_CTRLIDX_MASK
  #error FRIF_CTRLIDX_MASK already defined
#endif

#ifdef FRIF_DECOUPLED_TX_ENABLE
  #error FRIF_DECOUPLED_TX_ENABLE already defined
#endif

#ifdef FRIF_DECRX_INVALID
  #error FRIF_DECRX_INVALID already defined
#endif

#ifdef FRIF_DECRX_PAYLOAD_OFFSET
  #error FRIF_DECRX_PAYLOAD_OFFSET already defined
#endif

#ifdef FRIF_DECRX_VALID_BYTE_OFFSET
  #error FRIF_DECRX_VALID_BYTE_OFFSET already defined
#endif

#ifdef FRIF_ERRBITMASK_ACS_CH
  #error FRIF_ERRBITMASK_ACS_CH already defined
#endif

#ifdef FRIF_ERRBITMASK_NIT_CH
  #error FRIF_ERRBITMASK_NIT_CH already defined
#endif

#ifdef FRIF_ERRBITMASK_SW_CH
  #error FRIF_ERRBITMASK_SW_CH already defined
#endif

#ifdef FRIF_FRTRCV_INSTANCE_IDX
  #error FRIF_FRTRCV_INSTANCE_IDX already defined
#endif

#ifdef FRIF_FR_CTRLIDX
  #error FRIF_FR_CTRLIDX already defined
#endif

#ifdef FRIF_FR_INSTANCE_IDX
  #error FRIF_FR_INSTANCE_IDX already defined
#endif

#ifdef FRIF_GET_CHECKED_CONFIG_ADDR
  #error FRIF_GET_CHECKED_CONFIG_ADDR already defined
#endif

#ifdef FRIF_GET_CLSTPDUNUM
  #error FRIF_GET_CLSTPDUNUM already defined
#endif

#ifdef FRIF_GET_CNTLIMIT
  #error FRIF_GET_CNTLIMIT already defined
#endif

#ifdef FRIF_GET_CONFIG_ADDR
  #error FRIF_GET_CONFIG_ADDR already defined
#endif

#ifdef FRIF_GET_OWNERIDX
  #error FRIF_GET_OWNERIDX already defined
#endif

#ifdef FRIF_IMMEDIATE_RX_ENABLE
  #error FRIF_IMMEDIATE_RX_ENABLE already defined
#endif

#ifdef FRIF_INIT
  #error FRIF_INIT already defined
#endif

#ifdef FRIF_NUM_CTRL
  #error FRIF_NUM_CTRL already defined
#endif

#ifdef FRIF_OWNERIDX_MASK
  #error FRIF_OWNERIDX_MASK already defined
#endif

#ifdef FRIF_OWNERIDX_SHIFT
  #error FRIF_OWNERIDX_SHIFT already defined
#endif

#ifdef FRIF_PENDINGBIT_CLEARBITMASK
  #error FRIF_PENDINGBIT_CLEARBITMASK already defined
#endif

#ifdef FRIF_PENDINGBIT_MASK
  #error FRIF_PENDINGBIT_MASK already defined
#endif

#ifdef FRIF_PENDINGBIT_NONE
  #error FRIF_PENDINGBIT_NONE already defined
#endif

#ifdef FRIF_PENDINGBIT_SETBITMASK
  #error FRIF_PENDINGBIT_SETBITMASK already defined
#endif

#ifdef FRIF_PENDINGBIT_SHIFT
  #error FRIF_PENDINGBIT_SHIFT already defined
#endif

#ifdef FRIF_SYNCSTATE_ASYNC
  #error FRIF_SYNCSTATE_ASYNC already defined
#endif

#ifdef FRIF_SYNCSTATE_SYNC
  #error FRIF_SYNCSTATE_SYNC already defined
#endif

#ifdef FRIF_TMPPAYLOADBUFFER_U32_LENGTH
  #error FRIF_TMPPAYLOADBUFFER_U32_LENGTH already defined
#endif

#ifdef FRIF_TXCNT_MASK
  #error FRIF_TXCNT_MASK already defined
#endif

#ifdef FRIF_TXCONFIRMATION_ENABLE
  #error FRIF_TXCONFIRMATION_ENABLE already defined
#endif

#ifdef FRIF_TXSTATUS_MAX_PDUS_PER_FRAME
  #error FRIF_TXSTATUS_MAX_PDUS_PER_FRAME already defined
#endif

#ifdef FRIF_TXSTATUS_NUM_WORDS
  #error FRIF_TXSTATUS_NUM_WORDS already defined
#endif

#ifdef FRIF_TXSTATUS_WORD_MASK
  #error FRIF_TXSTATUS_WORD_MASK already defined
#endif

#ifdef FRIF_TXSTATUS_WORD_SIZE
  #error FRIF_TXSTATUS_WORD_SIZE already defined
#endif

#ifdef FRIF_TXTYPE_DECOUPLED
  #error FRIF_TXTYPE_DECOUPLED already defined
#endif

#ifdef FRIF_TXTYPE_MASK
  #error FRIF_TXTYPE_MASK already defined
#endif

#ifdef FRIF_TXTYPE_SHIFT
  #error FRIF_TXTYPE_SHIFT already defined
#endif

#ifdef FRIF_UB_BITPOS_MASK
  #error FRIF_UB_BITPOS_MASK already defined
#endif

#ifdef FRIF_UB_CLEARBITMASK
  #error FRIF_UB_CLEARBITMASK already defined
#endif

#ifdef FRIF_UB_GETBITMASK
  #error FRIF_UB_GETBITMASK already defined
#endif

#ifdef FRIF_UB_GETBITPOS
  #error FRIF_UB_GETBITPOS already defined
#endif

#ifdef FRIF_UB_SETBITMASK
  #error FRIF_UB_SETBITMASK already defined
#endif

#ifdef FRIF_UNINIT
  #error FRIF_UNINIT already defined
#endif

#ifdef FRIF_UPDATEBIT_NONE
  #error FRIF_UPDATEBIT_NONE already defined
#endif

#ifdef FrIf_Call_Fr
  #error FrIf_Call_Fr already defined
#endif

#ifdef FrIf_Call_FrTrcv
  #error FrIf_Call_FrTrcv already defined
#endif

#ifdef FrIf_Call_FrTrcv_Tmp
  #error FrIf_Call_FrTrcv_Tmp already defined
#endif

#ifdef FrIf_Call_FrTrcv_Tmp1
  #error FrIf_Call_FrTrcv_Tmp1 already defined
#endif

#ifdef FrIf_Call_Fr_Arg0
  #error FrIf_Call_Fr_Arg0 already defined
#endif

#ifdef FrIf_Call_Fr_Arg1
  #error FrIf_Call_Fr_Arg1 already defined
#endif

#ifdef FrIf_Call_Fr_Arg2
  #error FrIf_Call_Fr_Arg2 already defined
#endif

#ifdef FrIf_Call_Fr_Arg3
  #error FrIf_Call_Fr_Arg3 already defined
#endif

#ifdef FrIf_Call_Fr_Arg4
  #error FrIf_Call_Fr_Arg4 already defined
#endif

#ifdef FrIf_Call_Fr_Arg5
  #error FrIf_Call_Fr_Arg5 already defined
#endif

#ifdef FrIf_Call_Fr_Arg6
  #error FrIf_Call_Fr_Arg6 already defined
#endif

#ifdef FrIf_Call_Fr_Arg8
  #error FrIf_Call_Fr_Arg8 already defined
#endif

#ifdef FrIf_Call_Fr_Tmp
  #error FrIf_Call_Fr_Tmp already defined
#endif

#ifdef FrIf_Call_Fr_Tmp1
  #error FrIf_Call_Fr_Tmp1 already defined
#endif

#ifdef FrIf_Det_ReportError
  #error FrIf_Det_ReportError already defined
#endif

#ifdef FrIf_Get_FrTrcvFunctionPtr
  #error FrIf_Get_FrTrcvFunctionPtr already defined
#endif

#ifdef FrIf_RootConfigPtr
  #error FrIf_RootConfigPtr already defined
#endif

#endif /* defined FRIF_GUARDS_H */
