/**
 * \file
 *
 * \brief AUTOSAR TcpIp
 *
 * This file contains the implementation of the AUTOSAR
 * module TcpIp.
 *
 * \version 3.5.13
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2021 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */
/* Editing futile - file generated by 'make compile' */

#ifndef TCPIP_MERGED_INCLUDES_H
#define TCPIP_MERGED_INCLUDES_H

/* BEWARE: if you think, you see duplicates only differing in case:
 * there are case-sensitive OSes - so fix the case!
 * Indented files stem from the merged_includes_foreign file in your
 * source tree and signify externally visible API files
 */

#include <TSMem.h>
#include <TSCompiler_Default.h>
#include <TSAutosar.h>
#include <TSAtomic_Assign.h>
#include <Std_Types.h>
#include <SchM_TcpIp.h>
#include <Eth_GeneralTypes.h>
#include <EthSM.h>
#include <EthIf.h>
#include <ComStack_Types.h>
#include <ComStack_Helpers.h>
#include <Base_Dbg.h>
 #include <TcpIp_Udp_Api.h>
 #include <TcpIp_Tcp_Api.h>
 #include <TcpIp_Socket_Api.h>
 #include <TcpIp_Ndp_Api.h>
 #include <TcpIp_Memory_Api.h>
 #include <TcpIp_Lcfg.h>
 #include <TcpIp_Ip_Api.h>
 #include <TcpIp_Generic_Int.h>
 #include <TcpIp_DhcpV6_Api.h>
 #include <TcpIp_DhcpV4_Api.h>
 #include <TcpIp_CfgTypes.h>
 #include <TcpIp_Cfg.h>
 #include <TcpIp_Api.h>

#endif /* defined TCPIP_MERGED_INCLUDES_H */
